# Generated by Django 3.1.5 on 2021-01-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
