# Generated by Django 3.1.5 on 2021-01-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_auto_20210129_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='normalize_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
