# Generated by Django 3.1.5 on 2021-01-29 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0004_user_normalize_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='normalize_username',
        ),
    ]
