# Generated by Django 3.1.5 on 2021-01-30 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0009_auto_20210129_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_ats',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafeteria.dish'),
        ),
    ]
