# Generated by Django 3.1.5 on 2021-01-30 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0010_auto_20210129_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_ats',
            new_name='created_at',
        ),
    ]
