# Generated by Django 3.1.5 on 2021-01-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0011_auto_20210129_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(default='2021-01-30', null=True),
        ),
    ]
