# Generated by Django 3.1.5 on 2021-01-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0012_auto_20210129_2133'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('employee', 'created_at')},
        ),
    ]
