# Generated by Django 3.1.5 on 2021-01-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0013_auto_20210129_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customizations',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
